title: Iyad Al-Sahwi
logo: /assets/images/photo.jpg
description:  Java and Kotlin Backend
  <br><br>
  <a href="https://www.linkedin.com/in/iyad-a-b4a631103/"> 
    <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> 
  </a>
theme: jekyll-theme-minimal
