title: <img src="assets/images/user.svg" style="vertical-align:-28%"> Iyad Al-Sahwi
logo: /assets/images/photo.jpg
description: Backend Development in Java and Kotlin 
  <br><br>
  <img src="assets/images/external-link.svg" style="vertical-align:-16%">
  <a href="https://www.linkedin.com/in/iyad-a-b4a631103"> 
    <img src="https://img.shields.io/badge/LinkedIn-0A66C2?logo=LinkedIn"> 
  </a>
  <a href="https://github.com/futchas">  
    <img src="https://img.shields.io/badge/GitHub-181717?logo=GitHub">
  </a>
github:
  is_user_page: false
theme: jekyll-theme-minimal
