title: <img src="assets/images/user.svg" style="vertical-align:-28%"> Iyad Al-Sahwi
logo: /assets/images/photo.jpg
description: <h4>Backend - Java, Kotlin and Spring Boot</h4>
  What I enjoy is Refactoring, APIs and DevOps tasks.
  What I can quickly help with is CI/CD Migrations, Java version upgrades and Dockerization of services. <br><br>
  
  <img src="/assets/images/location.svg" style="vertical-align:-15%"> Happy to work on projects in Berlin and Remote
  <br><br>
  
  <img src="/assets/images/external-link.svg" style="vertical-align:-16%">
  <a href="/assets/Profile_Iyad_Al-Sahwi.pdf">
    <img src="https://img.shields.io/badge/Profile%20PDF-054d4d">
  </a>

  <a href="https://www.linkedin.com/in/iyad-dev"> 
    <img src="https://img.shields.io/badge/LinkedIn-0A66C2?logo=LinkedIn"> 
  </a>
  <a href="https://github.com/futchas">  
    <img src="https://img.shields.io/badge/GitHub-181717?logo=GitHub">
  </a> <br><br>

  <b>Certificates:</b><br>
  <a href="/assets/certificates/Java_DevDays_Certificate.jpg">
    <img src="https://img.shields.io/badge/Java-054d4d" style="vertical-align:-20%">
  </a>
  <a href="/assets/certificates/Software_Architecture_Summit_Zertifikat.jpg">
    <img src="https://img.shields.io/badge/Architecture-054d4d" style="vertical-align:-20%">
  </a>
  <a href="/assets/certificates/DevOps_Certificate.jpg">
    <img src="https://img.shields.io/badge/DevOps-054d4d" style="vertical-align:-20%">
  </a>
  <a href="/assets/certificates/JavaScript_Zertifikat.jpg">
    <img src="https://img.shields.io/badge/JavaScript-054d4d" style="vertical-align:-20%">
  </a>
  <br><br><br>
  
  <a href="https://www.java.com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg" alt="java" width="40" height="40"/></a>
  <a href="https://kotlinlang.org" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/kotlinlang/kotlinlang-icon.svg" alt="kotlin" width="40" height="40"/></a>
  <a href="https://spring.io/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/springio/springio-icon.svg" alt="spring" width="40" height="40"/></a>
  <a href="https://aws.amazon.com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg" alt="aws" width="40" height="40"/></a>
  <a href="https://www.docker.com/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg" alt="docker" width="40" height="40"/></a>
  <a href="https://kubernetes.io" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/kubernetes/kubernetes-icon.svg" alt="kubernetes" width="40" height="40"/></a>
  <a href="https://nodejs.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg" alt="nodejs" width="40" height="40"/></a>
  <a href="https://www.typescriptlang.org/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg" alt="typescript" width="40" height="40"/></a>
  <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="40" height="40"/></a>
  <a href="https://git-scm.com/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="40" height="40"/></a>
  <a href="https://www.jenkins.io" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/jenkins/jenkins-icon.svg" alt="jenkins" width="40" height="40"/></a>
  <a href="https://circleci.com" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/circleci/circleci-icon.svg" alt="circleci" width="40" height="40"/></a>
  <a href="https://www.linux.org/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg" alt="linux" width="40" height="40"/></a>
  <a href="https://www.gnu.org/software/bash/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg" alt="bash" width="40" height="40"/></a>
  <a href="https://www.mysql.com/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg" alt="mysql" width="40" height="40"/></a>
  <a href="https://www.mongodb.com/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg" alt="mongodb" width="40" height="40"/></a>
  <a href="https://www.elastic.co/kibana" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/elasticco_kibana/elasticco_kibana-icon.svg" alt="kibana" width="40" height="40"/></a>
  <a href="https://kafka.apache.org/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/apache_kafka/apache_kafka-icon.svg" alt="kafka" width="40" height="40"/></a>

github:
  is_user_page: false
theme: jekyll-theme-minimal