title: Iyad Al-Sahwi
logo: /assets/images/photo.jpg
description:  Java and Kotlin Backend
  <br><br>
  <a href="https://www.linkedin.com/in/iyad-a-b4a631103"> 
    <img src="https://img.shields.io/badge/LinkedIn-0A66C2?logo=LinkedIn"> 
  </a>
  <a href="https://github.com/futchas/futchas.github.io">  
    <img src="https://img.shields.io/badge/GitHub-181717?logo=GitHub">
  </a>
github:
  is_user_page: false
theme: jekyll-theme-minimal
